//==============================================================================
// ISP-CSIIR HLS Top Module Testbench
//==============================================================================
// Usage: ./hls_top_tb [input.hex] [output.hex] [config.json]
// Input patterns and configs are generated by Python scripts (in scripts/)
//==============================================================================

#ifndef ISP_CSIIR_HLS_TOP_TB_HPP
#define ISP_CSIIR_HLS_TOP_TB_HPP

#include <iostream>
#include <iomanip>
#include <fstream>
#include <sstream>
#include <string>
#include <cstdlib>
#include <cstdint>
#include <cstring>
#include <ap_fixed.h>
#include <hls_stream.h>
#include "isp_csiir_hls_top.cpp"

using namespace std;
using namespace hls;

// Image dimensions (can be overridden at compile time)
#ifndef TEST_WIDTH
#define TEST_WIDTH 16
#endif
#ifndef TEST_HEIGHT
#define TEST_HEIGHT 16
#endif

//==============================================================================
// Load input from hex file
//==============================================================================
bool load_input(const string& filename, ap_uint<10> img[TEST_HEIGHT][TEST_WIDTH]) {
    ifstream f(filename.c_str());
    if (!f.is_open()) {
        cerr << "Error: Cannot open input file: " << filename << endl;
        return false;
    }

    string line;
    int idx = 0;
    while (getline(f, line) && idx < TEST_WIDTH * TEST_HEIGHT) {
        if (line.empty() || line[0] == '#' || line[0] == '/')
            continue;
        istringstream iss(line);
        int val;
        if (iss >> hex >> val) {
            int y = idx / TEST_WIDTH;
            int x = idx % TEST_WIDTH;
            if (y < TEST_HEIGHT && x < TEST_WIDTH)
                img[y][x] = val;
            idx++;
        }
    }
    f.close();
    return true;
}

//==============================================================================
// Save output to hex file
//==============================================================================
bool save_output(const string& filename, ap_uint<10> output[TEST_HEIGHT][TEST_WIDTH]) {
    ofstream f(filename.c_str());
    if (!f.is_open()) {
        cerr << "Error: Cannot open output file: " << filename << endl;
        return false;
    }

    for (int y = 0; y < TEST_HEIGHT; y++) {
        for (int x = 0; x < TEST_WIDTH; x++) {
            f << hex << output[y][x].to_int() << "\n";
        }
    }
    f.close();
    return true;
}

//==============================================================================
// Process with HLS top using register struct
//==============================================================================
void process_top(ap_uint<10> input[TEST_HEIGHT][TEST_WIDTH],
                 ap_uint<10> output[TEST_HEIGHT][TEST_WIDTH],
                 ISPCSIIR_Regs& regs) {
    stream<axis_pixel_t> din_stream;
    stream<axis_pixel_t> dout_stream;

    // Write input
    for (int y = 0; y < TEST_HEIGHT; y++) {
        for (int x = 0; x < TEST_WIDTH; x++) {
            axis_pixel_t din;
            din.data = input[y][x];
            din.last = (y == TEST_HEIGHT-1 && x == TEST_WIDTH-1) ? 1 : 0;
            din.user = (y == 0 && x == 0) ? 1 : 0;
            din_stream.write(din);
        }
    }

    // Call HLS top with register struct
    isp_csiir_top(din_stream, dout_stream, regs);

    // Read output
    for (int y = 0; y < TEST_HEIGHT; y++) {
        for (int x = 0; x < TEST_WIDTH; x++) {
            axis_pixel_t dout = dout_stream.read();
            output[y][x] = dout.data;
        }
    }
}

//==============================================================================
// Main
//==============================================================================
int main(int argc, char* argv[]) {
    string input_file;
    string output_file;
    string config_file;

    // Parse arguments: [input.hex] [output.hex] [config.json]
    if (argc >= 2) input_file = argv[1];
    if (argc >= 3) output_file = argv[2];
    if (argc >= 4) config_file = argv[3];

    // Initialize registers with defaults
    ISPCSIIR_Regs regs;
    regs.reset();

    // Load config if provided
    if (!config_file.empty()) {
        cout << "\n--- Loading config from " << config_file << " ---" << endl;

        ifstream f(config_file.c_str());
        if (!f.is_open()) {
            cerr << "Error: Cannot open config file: " << config_file << endl;
            return 1;
        }

        string content((istreambuf_iterator<char>(f)), istreambuf_iterator<char>());
        f.close();

        // Parse width
        size_t pos = content.find("\"width\"");
        if (pos != string::npos) {
            pos = content.find(":", pos);
            regs.img_width = atoi(content.c_str() + pos + 1);
        }
        // Parse height
        pos = content.find("\"height\"");
        if (pos != string::npos) {
            pos = content.find(":", pos);
            regs.img_height = atoi(content.c_str() + pos + 1);
        }
        // Parse win_thresh array
        auto parse_array = [&](const char* name, ap_uint<8>* arr) {
            size_t pos = content.find(name);
            if (pos != string::npos) {
                pos = content.find("[", pos);
                size_t end = content.find("]", pos);
                string arr_str = content.substr(pos + 1, end - pos - 1);
                int idx = 0;
                size_t p = 0;
                while (p < arr_str.size() && idx < 4) {
                    while (p < arr_str.size() && !isdigit(arr_str[p]) && arr_str[p] != '-') p++;
                    if (p < arr_str.size()) {
                        arr[idx++] = atoi(arr_str.c_str() + p);
                        while (p < arr_str.size() && (isdigit(arr_str[p]) || arr_str[p] == '-')) p++;
                    }
                }
            }
        };
        parse_array("win_thresh", &regs.win_thresh0);
        parse_array("grad_clip", &regs.grad_clip0);
        parse_array("blend_ratio", &regs.blend_ratio0);
        // Parse edge_protect
        size_t pos_ep = content.find("\"edge_protect\"");
        if (pos_ep != string::npos) {
            pos_ep = content.find(":", pos_ep);
            regs.edge_protect = atoi(content.c_str() + pos_ep + 1);
        }
    }

    cout << "ISP-CSIIR HLS Top Test" << endl;
    cout << "======================" << endl;
    cout << "Image size: " << regs.img_width.to_int() << " x " << regs.img_height.to_int() << endl;

    // Check required input file
    if (input_file.empty()) {
        cerr << "Error: Input file required (use Python scripts to generate patterns)" << endl;
        cerr << "Usage: ./hls_top_tb [input.hex] [output.hex] [config.json]" << endl;
        return 1;
    }

    ap_uint<10> input[TEST_HEIGHT][TEST_WIDTH];
    ap_uint<10> output[TEST_HEIGHT][TEST_WIDTH];

    // Load input from hex file
    cout << "\n--- Loading from " << input_file << " ---" << endl;
    if (!load_input(input_file, input)) {
        return 1;
    }

    // Compute input range
    int min_in = 1024, max_in = 0;
    for (int y = 0; y < TEST_HEIGHT; y++)
        for (int x = 0; x < TEST_WIDTH; x++) {
            int val = input[y][x].to_int();
            min_in = min(min_in, val);
            max_in = max(max_in, val);
        }
    cout << "Input range: [" << min_in << ", " << max_in << "]" << endl;

    // Process
    process_top(input, output, regs);

    // Compute output range
    int min_out = 1024, max_out = 0;
    for (int y = 0; y < TEST_HEIGHT; y++)
        for (int x = 0; x < TEST_WIDTH; x++) {
            int val = output[y][x].to_int();
            min_out = min(min_out, val);
            max_out = max(max_out, val);
        }
    cout << "Output range: [" << min_out << ", " << max_out << "]" << endl;

    cout << "\nFirst 4x4 of output:" << endl;
    for (int y = 0; y < 4; y++) {
        cout << "  Row " << y << ": ";
        for (int x = 0; x < 4; x++) {
            cout << setw(4) << output[y][x].to_int() << " ";
        }
        cout << endl;
    }

    // Save output if filename provided
    if (!output_file.empty()) {
        if (save_output(output_file, output)) {
            cout << "\nOutput written to: " << output_file << endl;
        }
    }

    cout << "\nTest completed!" << endl;
    return 0;
}

#endif // ISP_CSIIR_HLS_TOP_TB_HPP