//==============================================================================
// ISP-CSIIR HLS Top Module Testbench
//==============================================================================
// Usage: ./hls_top_tb [input.hex] [output.hex] [config.json]
// Input patterns and configs are generated by Python scripts (in scripts/)
//==============================================================================

#ifndef ISP_CSIIR_HLS_TOP_TB_HPP
#define ISP_CSIIR_HLS_TOP_TB_HPP

#include <iostream>
#include <iomanip>
#include <fstream>
#include <sstream>
#include <string>
#include <cstdlib>
#include <cstdint>
#include <cstring>
#include <ap_fixed.h>
#include <hls_stream.h>
#include "isp_csiir_hls_top.cpp"

using namespace std;
using namespace hls;

// Image dimensions (can be overridden at compile time)
#ifndef TEST_WIDTH
#define TEST_WIDTH 16
#endif
#ifndef TEST_HEIGHT
#define TEST_HEIGHT 16
#endif

//==============================================================================
// Register Class using HLS types
//==============================================================================
class ISPCSIIR_Registers {
public:
    // Image dimensions
    ap_uint<16> img_width;
    ap_uint<16> img_height;

    // Window size thresholds [4]
    ap_uint<8> win_thresh0;
    ap_uint<8> win_thresh1;
    ap_uint<8> win_thresh2;
    ap_uint<8> win_thresh3;

    // Gradient clipping [4]
    ap_uint<8> grad_clip0;
    ap_uint<8> grad_clip1;
    ap_uint<8> grad_clip2;
    ap_uint<8> grad_clip3;

    // Blending ratios [4]
    ap_uint<8> blend_ratio0;
    ap_uint<8> blend_ratio1;
    ap_uint<8> blend_ratio2;
    ap_uint<8> blend_ratio3;

    // Edge protection
    ap_uint<8> edge_protect;

    // Static instance for HLS synthesis
    static ISPCSIIR_Registers& inst() {
        static ISPCSIIR_Registers instance;
        return instance;
    }

    // Set default values
    void reset() {
        img_width = TEST_WIDTH;
        img_height = TEST_HEIGHT;
        win_thresh0 = 100; win_thresh1 = 200; win_thresh2 = 400; win_thresh3 = 800;
        grad_clip0 = 15; grad_clip1 = 23; grad_clip2 = 31; grad_clip3 = 39;
        blend_ratio0 = 32; blend_ratio1 = 32; blend_ratio2 = 32; blend_ratio3 = 32;
        edge_protect = 32;
    }

    // Load from JSON config file
    bool load(const string& filename) {
        ifstream f(filename.c_str());
        if (!f.is_open()) {
            cerr << "Error: Cannot open config file: " << filename << endl;
            return false;
        }

        string content((istreambuf_iterator<char>(f)), istreambuf_iterator<char>());
        f.close();

        // Parse width
        size_t pos = content.find("\"width\"");
        if (pos != string::npos) {
            pos = content.find(":", pos);
            img_width = atoi(content.c_str() + pos + 1);
        }
        // Parse height
        pos = content.find("\"height\"");
        if (pos != string::npos) {
            pos = content.find(":", pos);
            img_height = atoi(content.c_str() + pos + 1);
        }
        // Parse win_thresh array
        parse_array(content, "win_thresh", [&](int idx, int val) {
            switch(idx) {
                case 0: win_thresh0 = val; break;
                case 1: win_thresh1 = val; break;
                case 2: win_thresh2 = val; break;
                case 3: win_thresh3 = val; break;
            }
        });
        // Parse grad_clip array
        parse_array(content, "grad_clip", [&](int idx, int val) {
            switch(idx) {
                case 0: grad_clip0 = val; break;
                case 1: grad_clip1 = val; break;
                case 2: grad_clip2 = val; break;
                case 3: grad_clip3 = val; break;
            }
        });
        // Parse blend_ratio array
        parse_array(content, "blend_ratio", [&](int idx, int val) {
            switch(idx) {
                case 0: blend_ratio0 = val; break;
                case 1: blend_ratio1 = val; break;
                case 2: blend_ratio2 = val; break;
                case 3: blend_ratio3 = val; break;
            }
        });
        // Parse edge_protect
        pos = content.find("\"edge_protect\"");
        if (pos != string::npos) {
            pos = content.find(":", pos);
            edge_protect = atoi(content.c_str() + pos + 1);
        }

        return true;
    }

private:
    ISPCSIIR_Registers() { reset(); }

    // Helper to parse JSON array
    template<typename F>
    void parse_array(const string& content, const char* name, F&& setter) {
        size_t pos = content.find(name);
        if (pos != string::npos) {
            pos = content.find("[", pos);
            size_t end = content.find("]", pos);
            string arr = content.substr(pos + 1, end - pos - 1);
            int idx = 0;
            size_t p = 0;
            while (p < arr.size() && idx < 4) {
                while (p < arr.size() && !isdigit(arr[p]) && arr[p] != '-') p++;
                if (p < arr.size()) {
                    int val = atoi(arr.c_str() + p);
                    setter(idx++, val);
                    while (p < arr.size() && (isdigit(arr[p]) || arr[p] == '-')) p++;
                }
            }
        }
    }
};

//==============================================================================
// Load input from hex file
//==============================================================================
bool load_input(const string& filename, ap_uint<10> img[TEST_HEIGHT][TEST_WIDTH]) {
    ifstream f(filename.c_str());
    if (!f.is_open()) {
        cerr << "Error: Cannot open input file: " << filename << endl;
        return false;
    }

    string line;
    int idx = 0;
    while (getline(f, line) && idx < TEST_WIDTH * TEST_HEIGHT) {
        if (line.empty() || line[0] == '#' || line[0] == '/')
            continue;
        istringstream iss(line);
        int val;
        if (iss >> hex >> val) {
            int y = idx / TEST_WIDTH;
            int x = idx % TEST_WIDTH;
            if (y < TEST_HEIGHT && x < TEST_WIDTH)
                img[y][x] = val;
            idx++;
        }
    }
    f.close();
    return true;
}

//==============================================================================
// Save output to hex file
//==============================================================================
bool save_output(const string& filename, ap_uint<10> output[TEST_HEIGHT][TEST_WIDTH]) {
    ofstream f(filename.c_str());
    if (!f.is_open()) {
        cerr << "Error: Cannot open output file: " << filename << endl;
        return false;
    }

    for (int y = 0; y < TEST_HEIGHT; y++) {
        for (int x = 0; x < TEST_WIDTH; x++) {
            f << hex << output[y][x].to_int() << "\n";
        }
    }
    f.close();
    return true;
}

//==============================================================================
// Process with HLS top using register class
//==============================================================================
void process_top(ap_uint<10> input[TEST_HEIGHT][TEST_WIDTH],
                 ap_uint<10> output[TEST_HEIGHT][TEST_WIDTH],
                 ISPCSIIR_Registers& regs) {
    stream<axis_pixel_t> din_stream;
    stream<axis_pixel_t> dout_stream;

    // Write input
    for (int y = 0; y < TEST_HEIGHT; y++) {
        for (int x = 0; x < TEST_WIDTH; x++) {
            axis_pixel_t din;
            din.data = input[y][x];
            din.last = (y == TEST_HEIGHT-1 && x == TEST_WIDTH-1) ? 1 : 0;
            din.user = (y == 0 && x == 0) ? 1 : 0;
            din_stream.write(din);
        }
    }

    // Call HLS top with registers
    isp_csiir_top(din_stream, dout_stream,
                  regs.img_width, regs.img_height,
                  regs.win_thresh0, regs.win_thresh1, regs.win_thresh2, regs.win_thresh3,
                  regs.grad_clip0, regs.grad_clip1, regs.grad_clip2, regs.grad_clip3,
                  regs.blend_ratio0, regs.blend_ratio1, regs.blend_ratio2, regs.blend_ratio3,
                  regs.edge_protect);

    // Read output
    for (int y = 0; y < TEST_HEIGHT; y++) {
        for (int x = 0; x < TEST_WIDTH; x++) {
            axis_pixel_t dout = dout_stream.read();
            output[y][x] = dout.data;
        }
    }
}

//==============================================================================
// Main
//==============================================================================
int main(int argc, char* argv[]) {
    string input_file;
    string output_file;
    string config_file;

    // Parse arguments: [input.hex] [output.hex] [config.json]
    if (argc >= 2) input_file = argv[1];
    if (argc >= 3) output_file = argv[2];
    if (argc >= 4) config_file = argv[3];

    // Get register instance
    ISPCSIIR_Registers& regs = ISPCSIIR_Registers::inst();
    regs.reset();

    // Load config if provided
    if (!config_file.empty()) {
        cout << "\n--- Loading config from " << config_file << " ---" << endl;
        if (!regs.load(config_file)) {
            return 1;
        }
    }

    cout << "ISP-CSIIR HLS Top Test" << endl;
    cout << "======================" << endl;
    cout << "Image size: " << regs.img_width.to_int() << " x " << regs.img_height.to_int() << endl;

    // Check required input file
    if (input_file.empty()) {
        cerr << "Error: Input file required (use Python scripts to generate patterns)" << endl;
        cerr << "Usage: ./hls_top_tb [input.hex] [output.hex] [config.json]" << endl;
        return 1;
    }

    ap_uint<10> input[TEST_HEIGHT][TEST_WIDTH];
    ap_uint<10> output[TEST_HEIGHT][TEST_WIDTH];

    // Load input from hex file
    cout << "\n--- Loading from " << input_file << " ---" << endl;
    if (!load_input(input_file, input)) {
        return 1;
    }

    // Compute input range
    int min_in = 1024, max_in = 0;
    for (int y = 0; y < TEST_HEIGHT; y++)
        for (int x = 0; x < TEST_WIDTH; x++) {
            int val = input[y][x].to_int();
            min_in = min(min_in, val);
            max_in = max(max_in, val);
        }
    cout << "Input range: [" << min_in << ", " << max_in << "]" << endl;

    // Process
    process_top(input, output, regs);

    // Compute output range
    int min_out = 1024, max_out = 0;
    for (int y = 0; y < TEST_HEIGHT; y++)
        for (int x = 0; x < TEST_WIDTH; x++) {
            int val = output[y][x].to_int();
            min_out = min(min_out, val);
            max_out = max(max_out, val);
        }
    cout << "Output range: [" << min_out << ", " << max_out << "]" << endl;

    cout << "\nFirst 4x4 of output:" << endl;
    for (int y = 0; y < 4; y++) {
        cout << "  Row " << y << ": ";
        for (int x = 0; x < 4; x++) {
            cout << setw(4) << output[y][x].to_int() << " ";
        }
        cout << endl;
    }

    // Save output if filename provided
    if (!output_file.empty()) {
        if (save_output(output_file, output)) {
            cout << "\nOutput written to: " << output_file << endl;
        }
    }

    cout << "\nTest completed!" << endl;
    return 0;
}

#endif // ISP_CSIIR_HLS_TOP_TB_HPP